### ISSUE TITLE
Possible Deprecation of Google Integration?

### ISSUE THREAD

**Issue by chrisaligent** [FriendsOfOro/OroCustomerTrackingBundle#2]
Oro 3.1.7 included references to a new Google Analytics bundle, which is currently unpublished.
Once published, this should be examined to see if it overlaps with this bundle. If so, we should remove Google Analytics (and GTM?) support from this Bundle, unless ours provides more functionality (eg future GA Ecommerce Tracking support).

In such a case, we should attempt to automatically disable/block the core Oro bundle from injecting GA/GTM code if this bundle is installed, as having both active simultaneously is a performance hit.

**Comment by mbessolov** [comment]
@chrisaligent FYI, GTM integration is published now at https://github.com/oroinc/google-tag-manager

**Comment by chrisaligent** [comment]
Removed GTM in #3 as part of 4.1 upgrade, will leave in place on 3.1.x branch for now as I don't think this Bundle has been used much. We are about to install it for a client on 4.1.x.
